import {
  Anchor,
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleQuestionMark,
  Download,
  Ellipsis,
  ExternalLink,
  Folder,
  FolderMinus,
  FolderPlus,
  Globe,
  Layers,
  LogOut,
  Plus,
  RotateCw,
  Rss,
  Search,
  SlidersHorizontal,
  SquarePen,
  Star,
  TextAlignJustify,
  Trash,
  Upload,
  X,
  createElement,
} from "lucide";
import type { IconNode, SVGProps } from "lucide";

const svg = (icon: IconNode, attrs?: SVGProps) => createElement(icon, attrs).outerHTML;

export default {
  anchor: svg(Anchor),
  "alert-circle": svg(CircleAlert),
  assorted: svg(TextAlignJustify),
  "book-open": svg(BookOpen),
  check: svg(Check),
  "chevron-down": svg(ChevronDown),
  "chevron-left": svg(ChevronLeft),
  "chevron-right": svg(ChevronRight),
  "chevron-up": svg(ChevronUp),
  circle: svg(Circle),
  "circle-full": svg(Circle, { fill: "currentColor" }),
  download: svg(Download),
  edit: svg(SquarePen),
  "external-link": svg(ExternalLink),
  folder: svg(Folder),
  "folder-minus": svg(FolderMinus),
  "folder-plus": svg(FolderPlus),
  globe: svg(Globe),
  "help-circle": svg(CircleQuestionMark),
  layers: svg(Layers),
  "log-out": svg(LogOut),
  "more-horizontal": svg(Ellipsis),
  plus: svg(Plus),
  "rotate-cw": svg(RotateCw),
  rss: svg(Rss),
  search: svg(Search),
  sliders: svg(SlidersHorizontal),
  star: svg(Star),
  "star-full": svg(Star, { fill: "currentColor" }),
  trash: svg(Trash),
  upload: svg(Upload),
  x: svg(X),
};
