name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      YARR_POSTGRES_TEST_IMAGE: postgres:17-alpine

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: make test
