name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'

    - name: Run tests
      run: go test -tags "sqlite_foreign_keys sqlite_json" -race -count=1 ./...

    - name: Build binary
      run: make host
